#!/usr/bin/env python3
"""
Generate and optionally run a Tamarin multihop Lightning Network theory
for an arbitrary number of hops.

Usage:
    python3 generate_multihop.py <hops> [--run] [--out FILE]

    hops   Total number of payment hops (channels).
           hops=3 means S -> F1 -> R  (1 intermediary)
           hops=4 means S -> F1 -> F2 -> R  (2 intermediaries)
           hops=N means N-2 intermediaries and N channels.

    --run  Run tamarin-prover --prove on the generated file.
    --out  Write theory to FILE (default: multihop_<hops>hop.spthy).
"""

import argparse
import subprocess
import sys
import os

# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def party(i, total_hops):
    """Return the party name at position i (0=Sender, total_hops-1=Receiver)."""
    if i == 0:
        return '$Sender'
    if i == total_hops - 1:
        return '$Receiver'
    return f'$F{i}'

def party_bare(i, total_hops):
    return party(i, total_hops).lstrip('$')

def ptr(i, total_hops):
    """Channel pointer variable between party i and i+1."""
    a = party_bare(i, total_hops)
    b = party_bare(i + 1, total_hops)
    return f'ptr{a}{b}'

def htlc_tag(i):
    return f"'htlc{i}'"

def ltk(i, total_hops):
    name = party_bare(i, total_hops)
    return f'ltk{name}'

def pk(i, total_hops):
    name = party_bare(i, total_hops)
    return f'pk{name}'

def sig(i, total_hops):
    name = party_bare(i, total_hops)
    return f'sig{name}'


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def gen_header(hops):
    intermediaries = hops - 2
    parties = ['Sender'] + [f'F{i}' for i in range(1, intermediaries + 1)] + ['Receiver']
    return f"""\
// Auto-generated {hops}-hop Lightning Network theory.
// Hops: {' -> '.join(parties)}
// Generated by generate_multihop.py
theory multihop_{hops}hop
begin

#include "3.splib"
"""


def gen_receiver_create_invoice():
    return """\
rule Receiver_Create_Invoice:
    let y = h(~x)
        invoice = <$Receiver, $Sender, y>
        sigR    = sign(invoice, ltkReceiver)
    in
    [ Fr(~x), !Ltk($Receiver, ltkReceiver) ]
    --[ InvoiceCreated($Receiver, $Sender, y),
        SecretPreimage($Receiver, ~x) ]->
    [ ReceiverInv($Receiver, $Sender, ~x),
      Out(<'SecretRS', invoice, sigR>) ]
"""


def gen_sender_offer(hops):
    p0 = party(0, hops)    # $Sender
    p1 = party(1, hops)    # $F1
    ch = ptr(0, hops)      # ptrSenderF1
    ltkS = ltk(0, hops)
    sigS = sig(0, hops)
    return f"""\
rule Sender_Offer_HTLC:
    let invoice = <$Receiver, $Sender, y>
        offer   = <{htlc_tag(1)}, {ch}, {p0}, {p1}, y>
        {sigS}  = sign(offer, {ltkS})
    in
    [ In(<'SecretRS', invoice, sigR>),
      !Pk($Receiver, pkReceiver),
      !Ltk({p0}, {ltkS}),
      !ChannelConnect({ch}, {p0}, {p1}) ]
    --[ HTLCOffered({p0}, {p1}, {ch}, y),
        HTLCAdded({ch}, y),
        Eq(verify(sigR, invoice, pkReceiver), true) ]->
    [ SenderPending({p0}, {p1}, $Receiver, {ch}, y),
      Out(<{htlc_tag(1)}, {ch}, {p0}, {p1}, y, {sigS}>) ]
"""


def gen_forward_rule(hop_idx, hops):
    """
    Generate the forwarding rule for intermediary at position hop_idx
    (1-indexed: hop_idx=1 is F1, etc.).
    hop_idx ranges from 1 to hops-2.
    """
    prev_party  = party(hop_idx - 1, hops)
    this_party  = party(hop_idx,     hops)
    next_party  = party(hop_idx + 1, hops)
    ch_in       = ptr(hop_idx - 1, hops)
    ch_out      = ptr(hop_idx,     hops)
    tag_in      = htlc_tag(hop_idx)
    tag_out     = htlc_tag(hop_idx + 1)
    ltkPrev     = ltk(hop_idx - 1, hops)
    ltkThis     = ltk(hop_idx,     hops)
    sigPrev     = sig(hop_idx - 1, hops)
    sigThis     = sig(hop_idx,     hops)
    pkPrev      = pk(hop_idx - 1, hops)
    this_bare   = party_bare(hop_idx, hops)
    rule_name   = f'Forward_{this_bare}_HTLC'

    return f"""\
rule {rule_name}:
    let offer    = <{tag_in},  {ch_in},  {prev_party}, {this_party}, y>
        offerFwd = <{tag_out}, {ch_out}, {this_party}, {next_party}, y>
        {sigThis} = sign(offerFwd, {ltkThis})
    in
    [ In(<{tag_in}, {ch_in}, {prev_party}, {this_party}, y, {sigPrev}>),
      !Pk({prev_party}, {pkPrev}), !Ltk({this_party}, {ltkThis}),
      !ChannelConnect({ch_in},  {prev_party}, {this_party}),
      !ChannelConnect({ch_out}, {this_party}, {next_party}) ]
    --[ HTLCForwarded({this_party}, {next_party}, {prev_party}, {ch_out}, y),
        HTLCAdded({ch_out}, y),
        ForwardHTLC({this_party}, {ch_in}, {ch_out}, y),
        Neq({ch_in}, {ch_out}),
        Eq(verify({sigPrev}, offer, {pkPrev}), true) ]->
    [ IntermediaryPending({this_party}, {prev_party}, {next_party}, {ch_in}, {ch_out}, y),
      Out(<{tag_out}, {ch_out}, {this_party}, {next_party}, y, {sigThis}>) ]
"""


def gen_receiver_fulfill(hops):
    last_intermediary = party(hops - 2, hops)
    ch_last           = ptr(hops - 2, hops)
    tag_last          = htlc_tag(hops - 1)
    sigLast           = sig(hops - 2, hops)
    pkLast            = pk(hops - 2, hops)

    return f"""\
rule Receiver_Fulfill_HTLC:
    let y        = h(x)
        offerFwd = <{tag_last}, {ch_last}, {last_intermediary}, $Receiver, y>
    in
    [ ReceiverInv($Receiver, $Sender, x),
      In(<{tag_last}, {ch_last}, {last_intermediary}, $Receiver, y, {sigLast}>),
      !Pk({last_intermediary}, {pkLast}),
      !ChannelConnect({ch_last}, {last_intermediary}, $Receiver) ]
    --[ HTLCFulfilled($Receiver, {last_intermediary}, {ch_last}, y),
        PreimageReleased($Receiver, x),
        Redeemed({ch_last}, y),
        Eq(verify({sigLast}, offerFwd, {pkLast}), true) ]->
    [ Out(<'fulfill', {ch_last}, x>) ]
"""


def gen_intermediary_settle():
    return """\
rule Intermediary_Settle:
    [ IntermediaryPending(MidP, InP, OutP, ptrIn, ptrOut, y),
      In(<'fulfill', ptrOut, x>) ]
    --[ IntermediaryClaimed(MidP, InP, ptrIn, x),
        Redeemed(ptrIn, y),
        Eq(h(x), y) ]->
    [ Out(<'fulfill', ptrIn, x>) ]
"""


def gen_sender_settle():
    return """\
rule Sender_Settle:
    [ SenderPending($Sender, $F1, $Receiver, ptrSenderF1, y),
      In(<'fulfill', ptrSenderF1, x>) ]
    --[ SenderSettled($Sender, $F1, $Receiver, ptrSenderF1, x),
        PaymentComplete($Sender, $Receiver, h(x)),
        Redeemed(ptrSenderF1, y),
        Eq(h(x), y) ]->
    [ ]
"""


def gen_timeout_rules():
    return """\
rule Open_Timeout:
    [ !ChannelConnect(ptr, A, B) ]
    --[ TimedOut(ptr) ]->
    [ !Timeout(ptr) ]

rule Sender_Timeout_Refund:
    [ SenderPending($Sender, $F1, $Receiver, ptrSenderF1, y),
      !Timeout(ptrSenderF1) ]
    --[ HTLCRefunded($Sender, ptrSenderF1, y),
        Refunded(ptrSenderF1, y) ]->
    [ ]

rule Intermediary_Timeout_Refund:
    [ IntermediaryPending(MidP, InP, OutP, ptrIn, ptrOut, y),
      !Timeout(ptrOut) ]
    --[ HTLCRefunded(MidP, ptrOut, y),
        Refunded(ptrOut, y) ]->
    [ ]
"""


def gen_restrictions():
    return """\
restriction OneOutcomePerHTLC:
    "All ptr y #i #j.
       Redeemed(ptr, y) @ #i & Refunded(ptr, y) @ #j ==> F"

restriction Inequality:
    "All x y #i. Neq(x, y) @ #i ==> not(x = y)"

restriction Equality:
    "All x y #i. Eq(x, y) @ #i ==> x = y"

restriction OneTimeoutPerPtr:
    "All ptr #i #j. TimedOut(ptr) @ #i & TimedOut(ptr) @ #j ==> #i = #j"

// (T1) Redemption must happen before the channel's own timeout.
restriction RedeemBeforeTimeout:
    "All ptr y #i #j.
        Redeemed(ptr, y) @ #i & TimedOut(ptr) @ #j ==> #i < #j"

// (T2) CLTV-delta ordering: outgoing timeout fires strictly before
// incoming timeout.  Applies when both timeouts fire.
restriction ForwardTimeGap:
    "All P ptrIn ptrOut y #f #j #k.
        ForwardHTLC(P, ptrIn, ptrOut, y) @ #f
      & TimedOut(ptrOut) @ #j
      & TimedOut(ptrIn)  @ #k
     ==> #j < #k"

// (T3) Watcher obligation: if the outgoing HTLC is redeemed before the
// incoming timeout, the intermediary sweeps the incoming HTLC.
restriction IntermediaryMustClaim:
    "All P ptrIn ptrOut y #f #i #k.
        ForwardHTLC(P, ptrIn, ptrOut, y) @ #f
      & Redeemed(ptrOut, y) @ #i
      & TimedOut(ptrIn)  @ #k
      & #i < #k
     ==> Ex #l. Redeemed(ptrIn, y) @ #l"
"""


def gen_reuse_lemmas():
    return """\
lemma Ltk_Known_Implies_Compromised [reuse]:
    "All A ltk #i #j.
        KeyGen(A, ltk) @ #i
      & !KU(ltk) @ #j
     ==> Ex #r. LtkCompromised(A) @ #r"

lemma Invoice_Has_Secret_Preimage [reuse]:
    "All R S x #i.
        InvoiceCreated(R, S, h(x)) @ #i
     ==> SecretPreimage(R, x) @ #i"

lemma Preimage_Secret_Until_Released [reuse]:
    "All R x #i #j.
        SecretPreimage(R, x) @ #i
      & K(x) @ #j & #i = #j
     ==> Ex #k. PreimageReleased(R, x) @ #k & #k < #j"

lemma HTLC_On_Opened_Channel [reuse, use_induction]:
    "All ptr y #i.
        HTLCAdded(ptr, y) @ #i
     ==> Ex X Y #j. ChannelOpen(X, Y, ptr) @ #j & #j < #i"

lemma Refund_Requires_Timeout [reuse]:
    "All ptr y #i.
        Refunded(ptr, y) @ #i
     ==> Ex #j. TimedOut(ptr) @ #j & #j < #i"
"""


def gen_security_lemmas():
    return """\
lemma Settle_Requires_Receiver_Release:
    "All S F1 R ptr x #i #j.
        SenderSettled(S, F1, R, ptr, x) @ #i
      & InvoiceCreated(R, S, h(x)) @ #j
     ==> Ex #k. PreimageReleased(R, x) @ #k & #k < #i"

lemma Claim_Requires_Release:
    "All MidP InP ptrIn R x #i #j.
        IntermediaryClaimed(MidP, InP, ptrIn, x) @ #i
      & SecretPreimage(R, x) @ #j
     ==> Ex #k. PreimageReleased(R, x) @ #k & #k < #i"

lemma Settle_Excludes_Sender_Refund:
    "All S F1 R ptr x #i.
        SenderSettled(S, F1, R, ptr, x) @ #i
     ==> not (Ex #j. HTLCRefunded(S, ptr, h(x)) @ #j)"

lemma Invoice_Authenticates_Settlement:
    "All S F1 R ptr x #i.
        SenderSettled(S, F1, R, ptr, x) @ #i
     ==> (Ex #j. InvoiceCreated(R, S, h(x)) @ #j & #j < #i)
       | (Ex #r. LtkCompromised(R) @ #r & #r < #i)"

lemma Forged_Invoice_Requires_Key_Compromise:
    exists-trace
    "Ex S F1 R ptr x #i #r.
        SenderSettled(S, F1, R, ptr, x) @ #i
      & LtkCompromised(R) @ #r
      & not (Ex #j. InvoiceCreated(R, S, h(x)) @ #j)"

lemma Loss_Requires_Inaction:
    "All P ptrIn ptrOut y #i #j #k.
        ForwardHTLC(P, ptrIn, ptrOut, y) @ #i
      & Redeemed(ptrOut, y) @ #j
      & Refunded(ptrIn, y) @ #k
     ==> not (Ex #l. Redeemed(ptrIn, y) @ #l)"

// NOTE: Intermediary_Never_Loses requires a block-number-based CLTV model
// (decreasing deadlines assigned at channel open) to be provable without a
// circular restriction.  It is included as a property of interest; with the
// current T1-T3 timing model it will falsify because T2 is vacuous when
// TimedOut(ptrOut) does not fire.
lemma Intermediary_Never_Loses:
    "All P ptrIn ptrOut y #f #i #j.
        ForwardHTLC(P, ptrIn, ptrOut, y) @ #f
      & Redeemed(ptrOut, y) @ #i
      & Refunded(ptrIn, y) @ #j
     ==> Ex #r. LtkCompromised(P) @ #r"
"""


def gen_payment_possible_lemma(hops):
    """Generate the Multihop_Payment_Possible existence lemma."""
    intermediaries = hops - 2
    # Build variable names
    ptrs   = [ptr(i, hops) for i in range(hops - 1)]
    events = []
    time_vars = []

    # t1: InvoiceCreated
    t = 1
    events.append(f'InvoiceCreated(R, S, h(x)) @ #t{t}')
    time_vars.append(f'#t{t}')
    t += 1

    # t2: HTLCOffered
    events.append(f'HTLCOffered(S, F1, {ptrs[0]}, h(x)) @ #t{t}')
    time_vars.append(f'#t{t}')
    t += 1

    # intermediate forwards
    for i in range(1, intermediaries):
        fi   = f'F{i}'
        fi1  = f'F{i + 1}' if i + 1 <= intermediaries - 1 else 'R' if intermediaries == 1 else f'F{i+1}'
        # Actually need to handle the last intermediary forwarding to Receiver
        prev = f'F{i}'
        nxt  = f'F{i+1}' if i < intermediaries else 'R'
        sender_var = f'F{i-1}' if i > 1 else 'S'
        events.append(f'HTLCForwarded({prev}, {nxt}, {sender_var}, {ptrs[i]}, h(x)) @ #t{t}')
        time_vars.append(f'#t{t}')
        t += 1

    # HTLCFulfilled
    last_int = f'F{intermediaries}' if intermediaries > 0 else 'S'
    events.append(f'HTLCFulfilled(R, {last_int}, {ptrs[-1]}, h(x)) @ #t{t}')
    time_vars.append(f'#t{t}')
    t += 1

    # IntermediaryClaimed (reverse order)
    for i in range(intermediaries, 0, -1):
        fi   = f'F{i}'
        prev = f'F{i-1}' if i > 1 else 'S'
        events.append(f'IntermediaryClaimed({fi}, {prev}, {ptrs[i-1]}, x) @ #t{t}')
        time_vars.append(f'#t{t}')
        t += 1

    # SenderSettled
    events.append(f'SenderSettled(S, F1, R, {ptrs[0]}, x) @ #t{t}')
    time_vars.append(f'#t{t}')
    t_max = t

    # Build ordering chain
    ordering = ' & '.join(f'#t{i} < #t{i+1}' for i in range(1, t_max))

    # Build ptr variables
    ptr_vars = ' '.join(ptrs)
    # Intermediary vars
    int_vars = ' '.join(f'F{i}' for i in range(1, intermediaries + 1))

    event_str = '\n      & '.join(events)

    return f"""\
lemma Multihop_Payment_Possible:
    exists-trace
    "Ex S {int_vars} R {ptr_vars} x {'  '.join(time_vars)}.
        {event_str}
      & {ordering}
      & not (Ex P #r. LtkCompromised(P) @ #r)
      & not (Ex P p y2 #u. HTLCRefunded(P, p, y2) @ #u)"
"""


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(hops):
    if hops < 3:
        sys.exit("hops must be >= 3 (minimum: Sender -> F1 -> Receiver)")

    intermediaries = hops - 2
    parts = []

    parts.append(gen_header(hops))
    parts.append(gen_receiver_create_invoice())
    parts.append(gen_sender_offer(hops))

    for i in range(1, intermediaries + 1):
        parts.append(gen_forward_rule(i, hops))

    parts.append(gen_receiver_fulfill(hops))
    parts.append(gen_intermediary_settle())
    parts.append(gen_sender_settle())
    parts.append(gen_timeout_rules())
    parts.append(gen_restrictions())
    parts.append(gen_reuse_lemmas())
    parts.append(gen_security_lemmas())
    parts.append(gen_payment_possible_lemma(hops))
    parts.append("end\n")

    return '\n'.join(parts)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('hops', type=int,
                        help='Total number of payment hops (channels)')
    parser.add_argument('--run', action='store_true',
                        help='Run tamarin-prover --prove on the generated file')
    parser.add_argument('--lemma', default=None,
                        help='Prove only this lemma (default: all)')
    parser.add_argument('--out', default=None,
                        help='Output file (default: multihop_<hops>hop.spthy)')
    args = parser.parse_args()

    theory = generate(args.hops)

    out_file = args.out or f'multihop_{args.hops}hop.spthy'
    with open(out_file, 'w', encoding='ascii') as f:
        f.write(theory)
    print(f'Generated: {out_file}')

    if args.run:
        cmd = ['tamarin-prover', out_file, '--prove']
        if args.lemma:
            cmd[-1] = f'--prove={args.lemma}'
        cmd += ['--stop-on-trace=SEQDFS']
        print(f'Running: {" ".join(cmd)}')
        env = os.environ.copy()
        env['LANG'] = 'C.utf8'
        env['LC_ALL'] = 'C.utf8'
        result = subprocess.run(cmd, env=env, capture_output=True, text=True, errors='replace')
        # Print summary lines only
        for line in (result.stdout + result.stderr).splitlines():
            if any(k in line for k in ('verified', 'falsified', 'steps',
                                        'incomplete', 'WARNING', 'error')):
                print(line)
        sys.exit(result.returncode)


if __name__ == '__main__':
    main()
