#!/usr/bin/env python3
"""Build the single merged theory lightning_all.spthy from its sources.

Tamarin 1.10's preprocessor cannot nest #ifdef inside an inactive branch, but it
accepts flat conditions with `not`, `&`, `|` (precedence: not > & > |).  So every
block of the merged file carries one flat condition:

  (no flag)                         main model  (lightning.spthy)
  -D=NO_IMC / NO_OTF / NO_RBT       main model with one liveness restriction removed
  -D=NECESSITY                      (with the above) ForwardTimeGap not [reuse]
  -D=AUX -D=PTLC                    PTLC countermeasure
  -D=AUX -D=HTLC                    HTLC baseline (shared hash lock)
  -D=AUX -D=CLOCK | CLTV | TIMEOUT  timing models

Usage:  python3 build.py   (writes lightning_all.spthy next to this script)
"""
import difflib
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = {
    'MAIN': os.path.join(HERE, 'lightning.spthy'),
    'PTLC': os.path.join(ROOT, 'tamarin', 'ptlc', 'ptlc.spthy'),
    'HTLC': os.path.join(ROOT, 'tamarin', 'ptlc', 'htlc_baseline.spthy'),
    'CLOCK': os.path.join(ROOT, 'Clock.spthy'),
    'CLTV': os.path.join(ROOT, 'Cltv.spthy'),
    'TIMEOUT': os.path.join(ROOT, 'timeout.spthy'),
}
BUILTINS = 'builtins: hashing, signing, natural-numbers'


def body(path):
    """Text between `begin` and the final `end`, without builtins lines."""
    s = open(path).read()
    s = s[s.index('\nbegin') + len('\nbegin'):]
    s = s[:s.rindex('\nend')]
    s = re.sub(r'^builtins:.*\n', '', s, flags=re.M)
    return s.strip('\n')


def block(cond, text):
    text = text.strip('\n')
    return f'#ifdef {cond}\n{text}\n#endif\n' if text.strip() else ''


def flatten_main(text):
    """Turn the main file's one-level #ifdef X / #else / #endif into flat blocks."""
    out, cur, cond = [], [], 'not AUX'
    def flush():
        if cur:
            out.append(block(cond, '\n'.join(cur)))
            cur.clear()
    flag = None
    for line in text.split('\n'):
        m = re.match(r'#ifdef\s+(\w+)\s*$', line)
        if m:
            flush(); flag = m.group(1); cond = f'not AUX & {flag}'; continue
        if line.strip() == '#else':
            flush(); cond = f'not AUX & not {flag}'; continue
        if line.strip() == '#endif':
            flush(); flag = None; cond = 'not AUX'; continue
        cur.append(line)
    flush()
    return '\n'.join(out)


def items(text):
    """Split a model body into top-level items separated by blank lines,
    never splitting inside a /* ... */ comment."""
    out, cur = [], ''
    for c in re.split(r'\n\s*\n', text):
        cur = c if not cur else cur + '\n\n' + c
        if cur.count('/*') == cur.count('*/'):
            if cur.strip():
                out.append(cur.strip('\n'))
            cur = ''
    if cur.strip():
        out.append(cur.strip('\n'))
    return out


def merge_pair(a_text, b_text, a, b):
    """Share identical top-level items of two models; guard the rest per model."""
    A, B = items(a_text), items(b_text)
    both = f'AUX & {a} | AUX & {b}'
    out = []
    for op, i1, i2, j1, j2 in difflib.SequenceMatcher(a=A, b=B, autojunk=False).get_opcodes():
        if op == 'equal':
            out.append(block(both, '\n\n'.join(A[i1:i2])))
        else:
            out.append(block(f'AUX & {a}', '\n\n'.join(A[i1:i2])))
            out.append(block(f'AUX & {b}', '\n\n'.join(B[j1:j2])))
    return '\n'.join(x for x in out if x)


def main():
    header = __doc__.split('Usage:')[0].strip().split('\n', 2)[2].strip()
    parts = [
        'theory lightning',
        'begin',
        '',
        '/*\n  Lightning multi-hop payments: main model and auxiliary models in one file.\n'
        '  Generated by build.py -- edit the sources, not this file.\n\n  '
        + header.replace('\n', '\n  ') + '\n*/',
        '',
        BUILTINS,
        '',
        '// ======================= main model =======================',
        flatten_main(body(SRC['MAIN'])),
        '// ============ PTLC countermeasure / HTLC baseline ============',
        merge_pair(body(SRC['PTLC']), body(SRC['HTLC']), 'PTLC', 'HTLC'),
        '// ======================= timing models =======================',
        block('AUX & CLOCK', body(SRC['CLOCK'])),
        block('AUX & CLTV', body(SRC['CLTV'])),
        block('AUX & TIMEOUT', body(SRC['TIMEOUT'])),
        'end',
        '',
    ]
    dst = os.path.join(HERE, 'lightning_all.spthy')
    open(dst, 'w').write('\n'.join(parts))
    print(dst, os.path.getsize(dst), 'bytes')


if __name__ == '__main__':
    main()
